version: "3"
services:
  app:
    build: ./app
    volumes:
      - ./app/smart_controller_app:/app
      - socket:/tmp
    command: uwsgi --ini /app/app.ini

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      - socket:/tmp

volumes:
  socket: